name: 'Antibot'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  antibot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Block bot abusers
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_USERNAME: ${{ github.actor }}
          # blocks any users that follow a number of users above this
          # threshold, consider them as bot abusers.
          ANTIBOT_THRESHOLD: 20000
          # comma separated list of usernames to whitelist (do not block
          # even if above threshold)
          ANTIBOT_WHITELIST: ''
        run: |
          python antibot.py
