name: 'Antibot'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  antibot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Tidy dependencies
        run: go mod tidy
      - name: Block bot abusers
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_USERNAME: ${{ github.actor }}
          # blocks any users with a follwing count above this
          # threshold, consider them as bot abusers.
          ANTIBOT_THRESHOLD: 20000
          # comma separated list of usernames to whitelist (do
          # not block even if above threshold)
          ANTIBOT_WHITELIST: ''
        run: |
          go run main.go
          uuidgen > .keep_alive
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Keep alive